//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobiens.Connectors.Services.SharePoint.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sbs007-public.sharepoint.com/_vti_bin/copy.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_com_sobiens_demo_Copy {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_com_sobiens_demo_Copy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sbs007-public.sharepoint.com/_vti_bin/lists.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_SharePointListsWS_Lists {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_SharePointListsWS_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sbs007-public.sharepoint.com/_vti_bin/sitedata.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_SharePointSiteWS_SiteData {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_SharePointSiteWS_SiteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sbs007-public.sharepoint.com/_vti_bin/views.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_SharePointViewsWS_Views {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_SharePointViewsWS_Views"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sbs007-public.sharepoint.com/_vti_bin/webs.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_SharePointWebsWS_Webs {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_SharePointWebsWS_Webs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.sobiens.com/_vti_bin/versions.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_SharePointVersionsWS_Versions {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_SharePointVersionsWS_Versions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://win-ram4kem5k9l/_vti_bin/workflow.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_SharePointWorkflowWS_Workflow {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_SharePointWorkflowWS_Workflow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://win-ram4kem5k9l/_vti_bin/TaxonomyClientService.asmx")]
        public string Sobiens_Connectors_Services_SharePoint_SharePointTaxonomyWS_Taxonomy_x0020_web_x0020_service {
            get {
                return ((string)(this["Sobiens_Connectors_Services_SharePoint_SharePointTaxonomyWS_Taxonomy_x0020_web_x0" +
                    "020_service"]));
            }
        }
    }
}
