//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobiens.Office.SharePointOutlookConnector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/webs.asmx")]
        public string SharePointOutlookConnector_SharePointWebsWS_Webs {
            get {
                return ((string)(this["SharePointOutlookConnector_SharePointWebsWS_Webs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/lists.asmx")]
        public string SharePointOutlookConnector_SharePointListsWS_Lists {
            get {
                return ((string)(this["SharePointOutlookConnector_SharePointListsWS_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/copy.asmx")]
        public string SharePointOutlookConnector_SharePointCopyWS_Copy {
            get {
                return ((string)(this["SharePointOutlookConnector_SharePointCopyWS_Copy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/versions.asmx")]
        public string Sobiens_Office_SharePointOutlookConnector_SharePointVersionsWS_Versions {
            get {
                return ((string)(this["Sobiens_Office_SharePointOutlookConnector_SharePointVersionsWS_Versions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/Alerts.asmx")]
        public string Sobiens_Office_SharePointOutlookConnector_SharePointAlertsWS_Alerts {
            get {
                return ((string)(this["Sobiens_Office_SharePointOutlookConnector_SharePointAlertsWS_Alerts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/_layouts/AlertsWebSebService.asmx")]
        public string Sobiens_Office_SharePointOutlookConnector_SobiensAlertsWS_AlertsWebService {
            get {
                return ((string)(this["Sobiens_Office_SharePointOutlookConnector_SobiensAlertsWS_AlertsWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/views.asmx")]
        public string Sobiens_Office_SharePointOutlookConnector_SharePointViewsWS_Views {
            get {
                return ((string)(this["Sobiens_Office_SharePointOutlookConnector_SharePointViewsWS_Views"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.sobiens.com/activation.asmx")]
        public string Sobiens_Office_SharePointOutlookConnector_ActivationService_Activation {
            get {
                return ((string)(this["Sobiens_Office_SharePointOutlookConnector_ActivationService_Activation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/SiteData.asmx")]
        public string Sobiens_Office_SharePointOutlookConnector_SharePointSiteWS_SiteData {
            get {
                return ((string)(this["Sobiens_Office_SharePointOutlookConnector_SharePointSiteWS_SiteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/copy.asmx")]
        public string EmailUploader_SharePointCopyWS_Copy {
            get {
                return ((string)(this["EmailUploader_SharePointCopyWS_Copy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/lists.asmx")]
        public string EmailUploader_SharePointListsWS_Lists {
            get {
                return ((string)(this["EmailUploader_SharePointListsWS_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://moss/_vti_bin/webs.asmx")]
        public string EmailUploader_SharePointWebsWS_Webs {
            get {
                return ((string)(this["EmailUploader_SharePointWebsWS_Webs"]));
            }
        }
    }
}
