// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sobiens.Connectors.Studio.UI.Controls.CodeTemplates.WebAPI
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Sobiens.Connectors.Entities;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ControllerClassTemplate : ControllerClassTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write(@"
using SobyGrid_WebAPIExample.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.OData;

namespace SobyGrid_WebAPIExample.Controllers
{
    public class ");
            
            #line 24 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("ListController : ODataController\r\n    {\r\n        private TaskServiceContext db = " +
                    "new TaskServiceContext();\r\n\r\n        // GET api/");
            
            #line 28 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n        [EnableQuery]\r\n        public IQueryable<");
            
            #line 30 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("Record> Get");
            
            #line 30 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List()\r\n        {\r\n            return db.");
            
            #line 32 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List;\r\n        }\r\n\r\n\t\t");
            
            #line 35 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"

		string parametersWithOrder = string.Empty;
		string queryStringParameters = string.Empty;
		string functionParameters = string.Empty;
		string whereFilters = "e => ";
		string badRequestCheckParameters = string.Empty;

		for(int i=0;i<Fields.Count;i++){
			if(Fields[i].IsPrimary == false)
				continue;
			string fieldTypeString = "string";
			if (Fields[i].Type == FieldTypes.Boolean)
				fieldTypeString = "bool";
			else if (Fields[i].Type == FieldTypes.Number)
				fieldTypeString = "int";
			string keyName = "key";
			parametersWithOrder += ", " + keyName;
			queryStringParameters += ", [FromODataUri] " + fieldTypeString + " " + keyName;
			functionParameters += ", " + fieldTypeString + " " + keyName;
			badRequestCheckParameters += " || updateEntity." + Fields[i].Name + " != " + keyName;
			whereFilters += " e." + Fields[i].Name + " == " + keyName + "  && ";
		}
		if(parametersWithOrder.Length>0)
			parametersWithOrder = parametersWithOrder.Substring(1);
		if(queryStringParameters.Length>0)
			queryStringParameters = queryStringParameters.Substring(1);
		if(functionParameters.Length>0)
		    functionParameters = functionParameters.Substring(1);
		if(badRequestCheckParameters.Length>0)
			badRequestCheckParameters = badRequestCheckParameters.Substring(3);
		if(whereFilters.Length>0)
	        whereFilters = whereFilters.Substring(0, whereFilters.Length - 3);
		
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 69 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"

		if(parametersWithOrder.Length>0)
		{
		
            
            #line default
            #line hidden
            this.Write("        [EnableQuery]\r\n        public SingleResult<");
            
            #line 74 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("Record> Get(");
            
            #line 74 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            IQueryable<");
            
            #line 76 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("Record> result = db.");
            
            #line 76 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List.Where(");
            
            #line 76 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(whereFilters));
            
            #line default
            #line hidden
            this.Write(");\r\n            return SingleResult.Create(result);\r\n        }\r\n\r\n        public " +
                    "async System.Threading.Tasks.Task<IHttpActionResult> Post(");
            
            #line 80 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("Record addEntity)\r\n        {\r\n            if (!ModelState.IsValid)\r\n            {" +
                    "\r\n                return BadRequest(ModelState);\r\n            }\r\n            db." +
                    "");
            
            #line 86 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List.Add(addEntity);\r\n            await db.SaveChangesAsync();\r\n            retur" +
                    "n Created(addEntity);\r\n        }\r\n\r\n        public async System.Threading.Tasks." +
                    "Task<IHttpActionResult> Patch(");
            
            #line 91 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            
            #line default
            #line hidden
            this.Write(", Delta<");
            
            #line 91 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("Record> patchEntity)\r\n        {\r\n            if (!ModelState.IsValid)\r\n          " +
                    "  {\r\n                return BadRequest(ModelState);\r\n            }\r\n            " +
                    "var entity = await db.");
            
            #line 97 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List.FindAsync(new object[]{");
            
            #line 97 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parametersWithOrder));
            
            #line default
            #line hidden
            this.Write(@"});
            if (entity == null)
            {
                return NotFound();
            }
            patchEntity.Patch(entity);
            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RecordExists(");
            
            #line 109 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parametersWithOrder));
            
            #line default
            #line hidden
            this.Write(@"))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return Updated(entity);
        }

        public async System.Threading.Tasks.Task<IHttpActionResult> Put(");
            
            #line 121 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 121 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("Record updateEntity)\r\n        {\r\n            if (!ModelState.IsValid)\r\n          " +
                    "  {\r\n                return BadRequest(ModelState);\r\n            }\r\n            " +
                    "if (");
            
            #line 127 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(badRequestCheckParameters));
            
            #line default
            #line hidden
            this.Write(@")
            {
                return BadRequest();
            }
            db.Entry(updateEntity).State = EntityState.Modified;
            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RecordExists(");
            
            #line 138 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parametersWithOrder));
            
            #line default
            #line hidden
            this.Write(@"))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return Updated(updateEntity);
        }

        public async System.Threading.Tasks.Task<IHttpActionResult> Delete(");
            
            #line 150 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryStringParameters));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var deleteEntity = await db.");
            
            #line 152 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List.FindAsync(new object[]{");
            
            #line 152 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parametersWithOrder));
            
            #line default
            #line hidden
            this.Write("});\r\n            if (deleteEntity == null)\r\n            {\r\n                return" +
                    " NotFound();\r\n            }\r\n            db.");
            
            #line 157 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List.Remove(deleteEntity);\r\n            await db.SaveChangesAsync();\r\n           " +
                    " return StatusCode(HttpStatusCode.NoContent);\r\n        }\r\n        private bool R" +
                    "ecordExists(");
            
            #line 161 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionParameters));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return db.");
            
            #line 163 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("List.Count(");
            
            #line 163 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(whereFilters));
            
            #line default
            #line hidden
            this.Write(") > 0;\r\n        }\r\n\t\t");
            
            #line 165 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"

		}
		
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        protected override void Dispose(bool disposing)\r\n        {\r\n         " +
                    "   if (disposing)\r\n            {\r\n                db.Dispose();\r\n            }\r\n" +
                    "            base.Dispose(disposing);\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Projects\GitHub\Sobiens-Connectors\Solutions\Sobiens.Connectors.Studio.UI.Controls\CodeTemplates\WebAPI\ControllerClassTemplate.tt"

private string _TableNameField;

/// <summary>
/// Access the TableName parameter of the template.
/// </summary>
private string TableName
{
    get
    {
        return this._TableNameField;
    }
}

private global::Sobiens.Connectors.Entities.FieldCollection _FieldsField;

/// <summary>
/// Access the Fields parameter of the template.
/// </summary>
private global::Sobiens.Connectors.Entities.FieldCollection Fields
{
    get
    {
        return this._FieldsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool TableNameValueAcquired = false;
if (this.Session.ContainsKey("TableName"))
{
    this._TableNameField = ((string)(this.Session["TableName"]));
    TableNameValueAcquired = true;
}
if ((TableNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TableName");
    if ((data != null))
    {
        this._TableNameField = ((string)(data));
    }
}
bool FieldsValueAcquired = false;
if (this.Session.ContainsKey("Fields"))
{
    this._FieldsField = ((global::Sobiens.Connectors.Entities.FieldCollection)(this.Session["Fields"]));
    FieldsValueAcquired = true;
}
if ((FieldsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Fields");
    if ((data != null))
    {
        this._FieldsField = ((global::Sobiens.Connectors.Entities.FieldCollection)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ControllerClassTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
